# K FOLD & CROSS VALIDATION

In [4]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits
da=load_digits()


In [5]:
dir(da)

['DESCR', 'data', 'images', 'target', 'target_names']

In [9]:
import pandas as pd
import numpy as np
df=pd.DataFrame(da.data)
df.head()

0    1    2     3     4     5    6    7    8    9  ...    54   55   56  \
0  0.0  0.0  5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
1  0.0  0.0  0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
2  0.0  0.0  0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0 ...   5.0  0.0  0.0   
3  0.0  0.0  7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0 ...   9.0  0.0  0.0   
4  0.0  0.0  0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   

    57   58    59    60    61   62   63  
0  0.0  6.0  13.0  10.0   0.0  0.0  0.0  
1  0.0  0.0  11.0  16.0  10.0  0.0  0.0  
2  0.0  0.0   3.0  11.0  16.0  9.0  0.0  
3  0.0  7.0  13.0  13.0   9.0  0.0  0.0  
4  0.0  0.0   2.0  16.0   4.0  0.0  0.0  

[5 rows x 64 columns]

In [12]:
df['targt']=da.target
df.head()

0    1    2     3     4     5    6    7    8    9  ...     55   56   57  \
0  0.0  0.0  5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0  ...    0.0  0.0  0.0   
1  0.0  0.0  0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...    0.0  0.0  0.0   
2  0.0  0.0  0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0  ...    0.0  0.0  0.0   
3  0.0  0.0  7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0  ...    0.0  0.0  0.0   
4  0.0  0.0  0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0  ...    0.0  0.0  0.0   

    58    59    60    61   62   63  targt  
0  6.0  13.0  10.0   0.0  0.0  0.0      0  
1  0.0  11.0  16.0  10.0  0.0  0.0      1  
2  0.0   3.0  11.0  16.0  9.0  0.0      2  
3  7.0  13.0  13.0   9.0  0.0  0.0      3  
4  0.0   2.0  16.0   4.0  0.0  0.0      4  

[5 rows x 65 columns]

In [16]:
x=df.drop('targt',axis='columns')
x.head()

0    1    2     3     4     5    6    7    8    9  ...    54   55   56  \
0  0.0  0.0  5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
1  0.0  0.0  0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
2  0.0  0.0  0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0 ...   5.0  0.0  0.0   
3  0.0  0.0  7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0 ...   9.0  0.0  0.0   
4  0.0  0.0  0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   

    57   58    59    60    61   62   63  
0  0.0  6.0  13.0  10.0   0.0  0.0  0.0  
1  0.0  0.0  11.0  16.0  10.0  0.0  0.0  
2  0.0  0.0   3.0  11.0  16.0  9.0  0.0  
3  0.0  7.0  13.0  13.0   9.0  0.0  0.0  
4  0.0  0.0   2.0  16.0   4.0  0.0  0.0  

[5 rows x 64 columns]

In [18]:
y=df.targt


In [37]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split=train_test_split(x,y,test_size=0.3)

In [53]:
mod1=LogisticRegression()
mod2=SVC()
mod3=RandomForestClassifier()

In [67]:
mod1=LogisticRegression(solver='sag')
mod1.fit(X_train,y_train)
mod1.score(X_test,y_test)

C:\Users\hamza jamil\Anaconda3\lib\site-packages\sklearn\linear_model\sag.py:326: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)


0.9629629629629629

In [60]:
mod2=SVC(kernel='linear')
mod2.fit(X_train,y_train)
mod2.score(X_test,y_test)

0.9648148148148148

In [107]:
mod2.predict(X_test)

array([1, 3, 5, 3, 4, 8, 4, 5, 6, 6, 2, 8, 0, 1, 7, 3, 1, 2, 7, 5, 6, 2,
       5, 4, 5, 9, 9, 0, 0, 0, 3, 5, 9, 6, 8, 5, 5, 1, 7, 7, 2, 2, 2, 1,
       3, 8, 8, 4, 5, 6, 3, 4, 0, 6, 3, 1, 3, 1, 7, 6, 6, 2, 1, 6, 9, 4,
       4, 6, 3, 2, 4, 8, 6, 7, 9, 7, 6, 8, 5, 5, 0, 5, 0, 8, 9, 9, 7, 7,
       2, 7, 8, 9, 0, 6, 4, 6, 7, 7, 0, 9, 9, 3, 3, 5, 2, 2, 2, 1, 4, 4,
       0, 1, 5, 2, 1, 7, 0, 0, 0, 5, 1, 1, 3, 9, 5, 2, 0, 3, 8, 8, 8, 0,
       6, 4, 5, 3, 4, 9, 7, 1, 5, 1, 6, 7, 7, 1, 8, 1, 7, 1, 5, 1, 5, 8,
       6, 1, 3, 1, 0, 3, 9, 5, 7, 5, 7, 9, 5, 2, 4, 2, 3, 1, 2, 1, 4, 6,
       6, 9, 9, 3, 8, 5, 8, 7, 5, 2, 3, 4, 3, 5, 7, 5, 7, 7, 2, 5, 9, 8,
       0, 4, 7, 4, 0, 1, 5, 6, 0, 1, 6, 9, 7, 8, 6, 0, 1, 8, 4, 4, 1, 2,
       5, 7, 3, 7, 2, 0, 1, 1, 2, 9, 3, 4, 9, 9, 4, 7, 3, 0, 0, 9, 2, 8,
       2, 0, 7, 3, 1, 1, 1, 4, 4, 1, 5, 4, 2, 1, 1, 0, 8, 0, 2, 3, 5, 0,
       1, 5, 3, 0, 9, 3, 5, 1, 1, 0, 3, 3, 0, 2, 2, 4, 9, 4, 7, 2, 8, 8,
       9, 0, 2, 7, 9, 5, 8, 4, 6, 0, 4, 0, 5, 5, 4,

In [108]:
y_test

471     1
1074    3
1784    5
799     3
627     4
1067    8
1114    4
135     5
322     6
1441    6
956     2
1028    8
1336    0
1626    1
894     7
1090    3
210     1
214     2
300     7
1672    5
444     6
1600    2
1489    5
24      4
1741    5
975     9
325     9
334     0
458     0
1663    0
       ..
1040    1
189     3
1064    5
1518    3
1682    5
931     6
1091    4
1080    8
1680    3
679     5
109     5
1567    4
1287    0
1089    3
758     7
1335    0
1321    6
1059    0
1003    5
1050    1
1444    9
509     8
258     2
1514    1
194     4
1535    5
1299    2
1433    8
1592    0
890     8
Name: targt, Length: 540, dtype: int32

In [80]:
mod3=RandomForestClassifier(n_estimators=48)
mod3.fit(X_train,y_train)
mod3.score(X_test,y_test)

0.975925925925926

# CROSS VALIDATAION SCORE

In [89]:
from sklearn.model_selection import cross_val_score
#first for logistic clasifer
cross_val_score(LogisticRegression(solver='liblinear'),da.data,da.target,cv=4)

array([0.93612335, 0.92017738, 0.96420582, 0.90337079])

In [94]:
cross_val_score(SVC(kernel='linear'),da.data,da.target,cv=4)

array([0.95594714, 0.94235033, 0.96868009, 0.92808989])

In [99]:
cross_val_score(RandomForestClassifier(n_estimators=67),da.data,da.target,cv=4)

array([0.95154185, 0.92239468, 0.97986577, 0.94606742])

# CROSS VALIDATION AVERAGE

In [103]:
s1=cross_val_score(LogisticRegression(solver='liblinear'),da.data,da.target,cv=4)
np.average(s1)

0.9309693336703256

In [105]:
s2=cross_val_score(SVC(kernel='linear'),da.data,da.target,cv=4)
np.average(s2)

0.948766861571005

In [109]:
s3=cross_val_score(RandomForestClassifier(n_estimators=67),da.data,da.target,cv=4)
np.average(s3)

0.937149338396636

# EXCERCIES CORSS VALIDATION

In [169]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
ir=load_iris()
dir(ir)

['DESCR', 'data', 'feature_names', 'target', 'target_names']

In [170]:
import pandas as pd
import numpy as np
fm=pd.DataFrame(ir.data,columns=ir.feature_names)
fm.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [171]:
fm['targt']=ir.target
fm.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   targt  
0      0  
1      0  
2      0  
3      0  
4      0

In [172]:
fm['flower']=fm.targt.apply([lambda x : ir.target_names[x]])
fm.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   targt  flower  
0      0  setosa  
1      0  setosa  
2      0  setosa  
3      0  setosa  
4      0  setosa

In [173]:
xx=fm.drop(['targt','flower'],axis='columns')
yy=fm.targt

In [174]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(xx,yy,test_size=0.2)

In [175]:
#here we perform LogisticRegression 
m1=LogisticRegression()
m1.fit(X_train,y_train)
m1.score(X_test,y_test)

0.8666666666666667

In [176]:
#here we perform Decision tree
m2=DecisionTreeClassifier()
m2.fit(X_train,y_train)
m2.score(X_test,y_test)

0.9333333333333333

In [177]:
#here we perform SVC
m3=SVC()
m3.fit(X_train,y_train)
m3.score(X_test,y_test)

0.9666666666666667

In [178]:
#here we perform RANDOM FOREST
m4=RandomForestClassifier()
m4.fit(X_train,y_train)
m4.score(X_test,y_test)

0.9333333333333333

# HERE WE USE CROSS VALIDATION FUNCTION

In [179]:
from sklearn.model_selection import cross_val_score
import numpy as np

In [180]:
#logistic reggresion
cross_val_score(LogisticRegression(),ir.data,ir.target)

array([0.96078431, 0.92156863, 0.95833333])

In [181]:
#DECISION TREE
cross_val_score(DecisionTreeClassifier(),ir.data,ir.target)

array([0.98039216, 0.92156863, 0.97916667])

In [183]:
#SVM
cross_val_score(SVC(),ir.data,ir.target)

array([0.98039216, 0.96078431, 0.97916667])

In [184]:
#RANDOM FOREST
cross_val_score(RandomForestClassifier(),ir.data,ir.target)

array([0.98039216, 0.94117647, 0.97916667])

# OVER MODEL PERFOMANCE

In [185]:
c1=cross_val_score(LogisticRegression(),ir.data,ir.target)
np.average(c1)

0.9468954248366014

In [187]:
c2=cross_val_score(DecisionTreeClassifier(),ir.data,ir.target)
np.average(c2)

0.960375816993464

In [189]:
c3=cross_val_score(SVC(),ir.data,ir.target)
np.average(c3)

0.9734477124183006

In [190]:
c4=cross_val_score(RandomForestClassifier(),ir.data,ir.target)
np.average(c4)

0.960375816993464